// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oc2HVvWq8AjpeR1f3w0EZxMhPaKAgnM',
    appId: '1:950550432548:web:b665c10a8c2b7b974e81b1',
    messagingSenderId: '950550432548',
    projectId: 'bloodpoint-1c315',
    authDomain: 'bloodpoint-1c315.firebaseapp.com',
    storageBucket: 'bloodpoint-1c315.appspot.com',
    measurementId: 'G-43QGT4ZE0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJrd6quCEs0EcEU1iXQjQy5XycEpnNM8',
    appId: '1:950550432548:android:3b9583cd7bf6aa0a4e81b1',
    messagingSenderId: '950550432548',
    projectId: 'bloodpoint-1c315',
    storageBucket: 'bloodpoint-1c315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RTR_lnWeuvaXYSRH7DR8TQaUWfICIoY',
    appId: '1:950550432548:ios:26404f8a15f11e914e81b1',
    messagingSenderId: '950550432548',
    projectId: 'bloodpoint-1c315',
    storageBucket: 'bloodpoint-1c315.appspot.com',
    iosBundleId: 'com.example.bloodPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5RTR_lnWeuvaXYSRH7DR8TQaUWfICIoY',
    appId: '1:950550432548:ios:26404f8a15f11e914e81b1',
    messagingSenderId: '950550432548',
    projectId: 'bloodpoint-1c315',
    storageBucket: 'bloodpoint-1c315.appspot.com',
    iosBundleId: 'com.example.bloodPoint',
  );
}
